load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "build3",
    srcs = ["main.cpp"],
    deps = [
        "//examples/example3/lib1:lib1",
        "//examples/example3/lib2:lib2",
    ],
)
